[toolchain]
channel = "nightly"
components = [
  "rustc",
  "rustfmt",
  "rust-analyzer",
  "rustc-dev",
  "rust-src",
  "clippy",
]
targets = [
  "x86_64-unknown-linux-gnu",
  "wasm32-unknown-unknown",
  "wasm32-wasip1",
  "wasm32-wasip2",
]
profile = "default"
